name: Entregables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps: 
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual (para local, no necesario aquí)
        run: echo "Activación automática en Actions"

      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 6 - Instalar dependecias
        run: pip install -e .

      - name: Paso 7 - Ejecutar Script Principal
        run: python main.py

      - name: Paso 8 - Crear commit automático
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Entrega automática del CRUD
          commit_user_name: YonierAlexisQuiceno [GitHub Actions]
          commit_user_email: yonier.quiceno@iudigital.edu.co
          commit_author: Yonier Quiceno <yonier.quiceno@iudigital.edu.co>

